apiVersion: v1
kind: Service
metadata:
  name: lucky-web-app-service
spec:
  type: NodePort
  selector:
    app: lucky-web
    tier: frontend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30000